apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: opendatahub
  name: odhservicemonitor
spec:
  endpoints:
    - port: web # odh-operator, Argo
    - port: 8080-tcp # Jupyterhub
      path: "/metrics"
  selector:
    matchLabels:
      opendatahub.io/component: "true"
