apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yaml: |
      entryPoints:
        web:
          address: ":8081"

      providers:
        file:
          directory: "/watched/"
          watch: true
      
      api:
        insecure: true
        dashboard: true
        debug: true
      log:
        level: INFO