apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator-certified
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: seldon-deploy-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-deploy-operator.v1.2.1
