apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  creationTimestamp: null
  name: kfnbc
  namespace: kfnbc-odh
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      parameters:
      - name: SUPERSET_ADMIN_PASSWORD
        value: admin
      repoRef:
        name: manifests
        path: superset
    name: superset
  - kustomizeConfig:
      overlays:
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  - kustomizeConfig:
      overlays:
      - openshift
      repoRef:
        name: kf-manifests
        path: apps/jupyter/jupyter-web-app/upstream
    name: jupyter-web-app
  - kustomizeConfig:
      overlays:
      - kubeflow
      repoRef:
        name: kf-manifests
        path: apps/jupyter/notebook-controller/upstream
    name: notebook-controller
  - kustomizeConfig:
      repoRef:
        name: kf-manifests
        path: distributions/stacks/openshift
    name: kubeflow-apps
  repos:
  - name: kf-manifests
    uri: https://github.com/maroroman/manifests/tarball/kfnbc-oauth
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/v1.1.1
status: {}
