apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: odh-test
  namespace: mroman-odh-operator-testing
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: test
  repos:
  - name: manifests
    uri: https://github.com/maroroman/odh-manifests/tarball/core-manifest
  version: master
