apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-minimal-notebook"
    opendatahub.io/notebook-image-name: "Minimal Python"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with minimal dependency set to start experimenting with Jupyter environment."
    opendatahub.io/notebook-image-order: 10
  name: s2i-minimal-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.6"}]'
      opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version": "3.0.16"}, {"name": "Notebook","version": "6.4.0"}]'
      openshift.io/imported-from: quay.io/thoth-station/s2i-minimal-py38-notebook
      opendatahub.io/default-image: true
    from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-minimal-py38-notebook:v0.0.15
    name: "v0.0.15"
    referencePolicy:
      type: Local
