#!/bin/bash

dashboard_pods=$(oc get pods -l app=odh-dashboard --all-namespaces=true -o=jsonpath='{range .items[*].metadata}{.name}{"\n"}{end}')

# Prepare folder for logs
mkdir -p must-gather/odh-dashboard || echo "Error creating odh-dashboard directory"
echo $dashboard_pods
# Get logs from all KfDef namespaces
for i in $dashboard_pods;
do
# Get pod logs for all the pods
mkdir must-gather/odh-dashboard/$i || echo "Error creating odh-dashboard directory"
oc rsync $i:/opt/app-root/src/logs/adminActivity.log must-gather/odh-dashboard/$i/|| echo "Error getting logs from $i"

done

## Get Operator pod logs
# oc logs deployment/opendatahub-operator -n openshift-operators >> must-gather/odh-operator/pod.log

exit 0

