apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: recording-rules
    app: rhods
  name: rhods-rules
spec:
  groups:
  - name: rhods-usage.rules
    rules:
    - record: cluster:usage:consumption:rhods:cpu:seconds:rate5m
      expr: sum(rate(container_cpu_usage_seconds_total{container="",pod=~"jupyterhub-nb.*",namespace="redhat-ods-applications"}[5m]))
