kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-cluster
rules:
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - pods
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
      - config.openshift.io
    resources:
      - clusterversions
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
      - pods
      - events